// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.dow1.domain;

import com.sut.dow1.domain.Dow001;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Dow001_Roo_Configurable {
    
    declare @type: Dow001: @Configurable;
    
}
