// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.dow1.domain;

import com.sut.dow1.domain.Dow001;

privileged aspect Dow001_Roo_JavaBean {
    
    public String Dow001.getName() {
        return this.name;
    }
    
    public void Dow001.setName(String name) {
        this.name = name;
    }
    
}
